In [1]:
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from uuid import uuid4

import pandas as pd
import vertexai
from google import genai
from google.api_core.exceptions import Conflict, NotFound
from google.cloud import bigquery
from google.cloud import storage
from vertexai.language_models import TextEmbeddingModel

In [2]:
PROJECT_ID = "leafy-guide-497515-m4"
LOCATION = "us-central1"

BUCKET_NAME = "leafy-guide-497515-m4-vector-assets"

DATASET_ID = "ubuntu_log_auditor_rag"
LOG_TABLE_ID = "ubuntu_log_files"
DOCUMENT_TABLE_ID = "ubuntu_knowledge_documents"
CHUNK_TABLE_ID = "ubuntu_log_and_knowledge_chunks"
AUDIT_TABLE_ID = "ubuntu_audit_reports"

PLANNING_MODEL = "gemini-2.5-pro"
TEXT_MODEL = "gemini-2.5-flash"
TEXT_EMBEDDING_MODEL = "text-embedding-005"

CHUNK_SIZE_CHARS = 1200
CHUNK_OVERLAP_CHARS = 200
MAX_EMBEDDING_TEXT_CHARS = 3000

GCS_LOG_PREFIX = "ubuntu-log-auditor/logs"
GCS_AUDIT_PREFIX = "ubuntu-log-auditor/audits"
GCS_SCRIPT_PREFIX = "ubuntu-log-auditor/scripts"
GCS_SUMMARY_PREFIX = "ubuntu-log-auditor/summaries"

print("Configuration loaded.")
print("Project:", PROJECT_ID)
print("Location:", LOCATION)
print("Bucket:", BUCKET_NAME)
print("Dataset:", DATASET_ID)
print("Text model:", TEXT_MODEL)
print("Embedding model:", TEXT_EMBEDDING_MODEL)

Configuration loaded.
Project: leafy-guide-497515-m4
Location: us-central1
Bucket: leafy-guide-497515-m4-vector-assets
Dataset: ubuntu_log_auditor_rag
Text model: gemini-2.5-flash
Embedding model: text-embedding-005

In [3]:
vertexai.init(
    project=PROJECT_ID,
    location=LOCATION,
)

google_vertex_client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location=LOCATION,
)

storage_client = storage.Client(project=PROJECT_ID)
bucket = storage_client.bucket(BUCKET_NAME)

bigquery_client = bigquery.Client(project=PROJECT_ID)

text_embedding_model = TextEmbeddingModel.from_pretrained(
    TEXT_EMBEDDING_MODEL
)

print("Clients created.")
print("Bucket exists:", bucket.exists())
print("BigQuery project:", bigquery_client.project)
print("Text embedding model loaded.")

/home/lipov/projects/Python_practice_sessions_05/.venv/lib/python3.13/site-packages/vertexai/_model_garden/_model_garden_models.py:278: UserWarning: This feature is deprecated as of June 24, 2025 and will be removed on June 24, 2026. For details, see https://cloud.google.com/vertex-ai/generative-ai/docs/deprecations/genai-vertexai-sdk.
  warning_logs.show_deprecation_warning()

Clients created.
Bucket exists: True
BigQuery project: leafy-guide-497515-m4
Text embedding model loaded.

In [4]:
dataset_ref = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
dataset_ref.location = "EU"

try:
    dataset = bigquery_client.create_dataset(dataset_ref)
    print("Created dataset:", dataset.full_dataset_id)
except Conflict:
    dataset = bigquery_client.get_dataset(dataset_ref)
    print("Dataset already exists:", dataset.full_dataset_id)

log_table_ref = f"{PROJECT_ID}.{DATASET_ID}.{LOG_TABLE_ID}"
document_table_ref = f"{PROJECT_ID}.{DATASET_ID}.{DOCUMENT_TABLE_ID}"
chunk_table_ref = f"{PROJECT_ID}.{DATASET_ID}.{CHUNK_TABLE_ID}"
audit_table_ref = f"{PROJECT_ID}.{DATASET_ID}.{AUDIT_TABLE_ID}"

print("Log table:", log_table_ref)
print("Document table:", document_table_ref)
print("Chunk table:", chunk_table_ref)
print("Audit table:", audit_table_ref)

Created dataset: leafy-guide-497515-m4:ubuntu_log_auditor_rag
Log table: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_files
Document table: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_knowledge_documents
Chunk table: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_and_knowledge_chunks
Audit table: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_audit_reports

In [5]:
def ensure_bigquery_table(
    table_ref: str,
    schema: list[bigquery.SchemaField],
) -> bigquery.Table:
    try:
        table = bigquery_client.get_table(table_ref)
        print("Table already exists:", table.full_table_id)
        return table

    except NotFound:
        print("Table does not exist. Creating:", table_ref)

        table = bigquery.Table(
            table_ref,
            schema=schema,
        )

        created_table = bigquery_client.create_table(table)
        print("Created table:", created_table.full_table_id)

        return created_table

In [6]:
log_schema = [
    bigquery.SchemaField("log_file_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("log_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("log_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("host_name", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("scenario", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("severity_hint", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("content", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("gcs_uri", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
]

document_schema = [
    bigquery.SchemaField("document_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("document_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("topic", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("title", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("content", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("summary", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
]

chunk_schema = [
    bigquery.SchemaField("chunk_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("source_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("source_kind", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("source_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("chunk_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("global_chunk_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("source_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("topic", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("title", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("chunk_text", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("chunk_char_count", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("embedding_model", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("embedding", "FLOAT64", mode="REPEATED"),
    bigquery.SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
]

audit_schema = [
    bigquery.SchemaField("audit_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("question", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("risk_level", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("primary_issue", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("root_cause_hypothesis", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("audit_report", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("bash_script", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("audit_gcs_uri", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("script_gcs_uri", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("used_chunk_ids", "STRING", mode="REPEATED"),
    bigquery.SchemaField("used_sources", "STRING", mode="REPEATED"),
    bigquery.SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
]

In [7]:
log_table = ensure_bigquery_table(
    log_table_ref,
    log_schema,
)

document_table = ensure_bigquery_table(
    document_table_ref,
    document_schema,
)

chunk_table = ensure_bigquery_table(
    chunk_table_ref,
    chunk_schema,
)

audit_table = ensure_bigquery_table(
    audit_table_ref,
    audit_schema,
)

Table does not exist. Creating: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_files
Created table: leafy-guide-497515-m4:ubuntu_log_auditor_rag.ubuntu_log_files
Table does not exist. Creating: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_knowledge_documents
Created table: leafy-guide-497515-m4:ubuntu_log_auditor_rag.ubuntu_knowledge_documents
Table does not exist. Creating: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_and_knowledge_chunks
Created table: leafy-guide-497515-m4:ubuntu_log_auditor_rag.ubuntu_log_and_knowledge_chunks
Table does not exist. Creating: leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_audit_reports
Created table: leafy-guide-497515-m4:ubuntu_log_auditor_rag.ubuntu_audit_reports

In [8]:
def gcs_uri_from_blob_name(
    bucket_name: str,
    blob_name: str,
) -> str:
    return f"gs://{bucket_name}/{blob_name}"


def upload_text_to_gcs(
    text: str,
    *,
    blob_name: str,
    content_type: str = "text/plain",
) -> str:
    blob = bucket.blob(blob_name)

    blob.upload_from_string(
        text,
        content_type=content_type,
    )

    return gcs_uri_from_blob_name(
        bucket_name=BUCKET_NAME,
        blob_name=blob_name,
    )

In [9]:
def extract_json_object(text: str) -> dict:
    cleaned = text.strip()

    if cleaned.startswith("```json"):
        cleaned = cleaned.removeprefix("```json").strip()

    if cleaned.startswith("```"):
        cleaned = cleaned.removeprefix("```").strip()

    if cleaned.endswith("```"):
        cleaned = cleaned.removesuffix("```").strip()

    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start == -1 or end == -1:
        raise ValueError(f"No JSON object found in text: {text[:500]}")

    return json.loads(cleaned[start:end + 1])

In [10]:
ubuntu_auditor_brief = """
Create a synthetic Ubuntu system log auditing dataset.

The notebook should simulate a cloud-native log auditor for Ubuntu servers.
It should not read local /var/log files and should not save local files.
All generated logs, audit reports, scripts, and metadata must be stored in Google Cloud Storage and BigQuery.

The system should analyze:
- syslog-like system events
- dmesg-like kernel messages
- systemd service failures
- disk pressure warnings
- SSH authentication anomalies
- network instability
- package manager issues
- kernel driver warnings

The final assistant should:
- retrieve relevant log chunks and knowledge chunks semantically
- identify likely root cause
- rate operational risk
- propose safe diagnostic commands
- generate a cautious Bash mitigation script
- explicitly avoid destructive commands unless clearly justified
"""

print(ubuntu_auditor_brief)

Create a synthetic Ubuntu system log auditing dataset.

The notebook should simulate a cloud-native log auditor for Ubuntu servers.
It should not read local /var/log files and should not save local files.
All generated logs, audit reports, scripts, and metadata must be stored in Google Cloud Storage and BigQuery.

The system should analyze:
- syslog-like system events
- dmesg-like kernel messages
- systemd service failures
- disk pressure warnings
- SSH authentication anomalies
- network instability
- package manager issues
- kernel driver warnings

The final assistant should:
- retrieve relevant log chunks and knowledge chunks semantically
- identify likely root cause
- rate operational risk
- propose safe diagnostic commands
- generate a cautious Bash mitigation script
- explicitly avoid destructive commands unless clearly justified

In [11]:
log_specs = [
    {
        "log_number": 1,
        "log_type": "syslog",
        "host_name": "ubuntu-worker-01",
        "scenario": "disk pressure and journal growth causing service instability",
        "severity_hint": "high",
        "focus": "systemd journal growth, low disk space, apt cache, service restart loops",
    },
    {
        "log_number": 2,
        "log_type": "dmesg",
        "host_name": "ubuntu-gpu-node-02",
        "scenario": "kernel driver warnings and intermittent device reset",
        "severity_hint": "medium",
        "focus": "kernel ring buffer, PCIe device reset, driver timeout, I/O warning",
    },
    {
        "log_number": 3,
        "log_type": "authlog",
        "host_name": "ubuntu-api-03",
        "scenario": "SSH authentication anomaly with repeated failed login attempts",
        "severity_hint": "critical",
        "focus": "failed password attempts, invalid users, sudo session, accepted public key, suspicious source IP patterns",
    },
    {
        "log_number": 4,
        "log_type": "systemd",
        "host_name": "ubuntu-db-04",
        "scenario": "database service restart loop after configuration change",
        "severity_hint": "high",
        "focus": "systemd restart policy, failed unit, environment file mismatch, port binding conflict",
    },
    {
        "log_number": 5,
        "log_type": "network",
        "host_name": "ubuntu-edge-05",
        "scenario": "network instability with DNS failures and interface flaps",
        "severity_hint": "medium",
        "focus": "NetworkManager, DNS timeout, link down/up, packet loss, route changes",
    },
]

pd.DataFrame(log_specs)

,log_number,log_type,host_name,scenario,severity_hint,focus
0,1,syslog,ubuntu-worker-01,disk pressure and journal growth causing servi...,high,"systemd journal growth, low disk space, apt ca..."
1,2,dmesg,ubuntu-gpu-node-02,kernel driver warnings and intermittent device...,medium,"kernel ring buffer, PCIe device reset, driver ..."
2,3,authlog,ubuntu-api-03,SSH authentication anomaly with repeated faile...,critical,"failed password attempts, invalid users, sudo ..."
3,4,systemd,ubuntu-db-04,database service restart loop after configurat...,high,"systemd restart policy, failed unit, environme..."
4,5,network,ubuntu-edge-05,network instability with DNS failures and inte...,medium,"NetworkManager, DNS timeout, link down/up, pac..."

In [12]:
def generate_synthetic_ubuntu_log(spec: dict) -> str:
    prompt = f"""
You are generating a synthetic Ubuntu log file for a cloud log auditing lab.

Brief:
{ubuntu_auditor_brief}

Log specification:
{json.dumps(spec, indent=2, ensure_ascii=False)}

Create a realistic synthetic Linux log file.

Requirements:
- Use realistic Ubuntu log style.
- Include timestamps, hostnames, process names, PIDs where appropriate.
- Include 80 to 140 log lines.
- Include normal noise and relevant warning/error lines.
- Make the issue diagnosable but not too obvious.
- Do not include real secrets, real IP addresses, or real user data.
- Use documentation-safe private IP ranges only, such as 10.x.x.x, 172.16.x.x, 192.168.x.x.
- Do not mention that the log is synthetic.
"""

    response = google_vertex_client.models.generate_content(
        model=PLANNING_MODEL,
        contents=prompt,
    )

    return response.text.strip()

In [13]:
generated_logs = []

timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

for spec in log_specs:
    print("=" * 100)
    print("Generating log:", spec["log_type"], "|", spec["host_name"])

    content = generate_synthetic_ubuntu_log(spec)

    blob_name = (
        f"{GCS_LOG_PREFIX}/"
        f"{timestamp}/"
        f"{spec['log_number']:02d}_{spec['host_name']}_{spec['log_type']}.log"
    )

    gcs_uri = upload_text_to_gcs(
        content,
        blob_name=blob_name,
        content_type="text/plain",
    )

    log_row = {
        "log_file_id": str(uuid4()),
        "log_number": spec["log_number"],
        "log_type": spec["log_type"],
        "host_name": spec["host_name"],
        "scenario": spec["scenario"],
        "severity_hint": spec["severity_hint"],
        "content": content,
        "gcs_uri": gcs_uri,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    generated_logs.append(log_row)

    print("Lines:", len(content.splitlines()))
    print("GCS URI:", gcs_uri)
    print(content[:800])

====================================================================================================
Generating log: syslog | ubuntu-worker-01
Lines: 103
GCS URI: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254/01_ubuntu-worker-01_syslog.log
Oct 26 08:30:01 ubuntu-worker-01 systemd[1]: Starting Daily apt download activities...
Oct 26 08:30:02 ubuntu-worker-01 CRON[23101]: (root) CMD (   PATH="$PATH:/usr/sbin"  cd / && run-parts --report /etc/cron.hourly)
Oct 26 08:30:15 ubuntu-worker-01 sshd[23115]: Accepted publickey for cloud-user from 10.0.1.15 port 56284 ssh2: RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Oct 26 08:30:15 ubuntu-worker-01 systemd[1]: Created slice User Slice of UID 1000.
Oct 26 08:30:15 ubuntu-worker-01 systemd[1]: Starting User Runtime Directory /run/user/1000...
Oct 26 08:30:16 ubuntu-worker-01 systemd[1]: Started User Runtime Directory /run/user/1000.
Oct 26 08:30:16 ubuntu-worker-01 systemd[1]: Starting User Manager for UID 1000...
Oct 26 08:31:01 ubuntu-worker-01 systemd[1]: Starting Clean Up
====================================================================================================
Generating log: dmesg | ubuntu-gpu-node-02
Lines: 124
GCS URI: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254/02_ubuntu-gpu-node-02_dmesg.log
```
[217340.125112] systemd-journald[451]: Received client request to flush runtime journal.
[217345.881234] eth0: NIC Link is Up 10000 Mbps Full Duplex, Flow Control: RX/TX
[217345.881567] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[217351.450012] nf_conntrack: nf_conntrack: table full, dropping packet
[217351.450088] nf_conntrack: nf_conntrack: table full, dropping packet
[217360.102231] audit: type=1400 audit(1678886400.101:812): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/var/lib/sntp/sntp.log" pid=1102 comm="ntpd" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
[217382.910345] nvme 0000:03:00.0: controller is down; will reset: CSTS=0x1, PCI_STATUS=0x10
[217382.910355] nvme 0000:03:00.0: enabling device (0000 -> 0002)
[217383.153912] nvme nvme1: cr
====================================================================================================
Generating log: authlog | ubuntu-api-03
Lines: 99
GCS URI: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254/03_ubuntu-api-03_authlog.log
```
Oct 26 14:00:01 ubuntu-api-03 CRON[18101]: pam_unix(cron:session): session opened for user root by (uid=0)
Oct 26 14:00:01 ubuntu-api-03 CRON[18102]: (root) CMD (   /usr/lib/snapd/snapd-app-armor)
Oct 26 14:00:01 ubuntu-api-03 CRON[18101]: pam_unix(cron:session): session closed for user root
Oct 26 14:01:22 ubuntu-api-03 systemd[1]: Starting Daily apt download activities...
Oct 26 14:01:23 ubuntu-api-03 systemd[1]: Started Daily apt download activities.
Oct 26 14:03:15 ubuntu-api-03 sshd[18230]: Connection closed by authenticating user backup 192.168.10.25 port 51234 [preauth]
Oct 26 14:05:11 ubuntu-api-03 sshd[18255]: Failed password for invalid user admin from 172.18.34.112 port 48302 ssh2
Oct 26 14:05:13 ubuntu-api-03 sshd[18255]: Connection closed by authenticating user admin 172.1
====================================================================================================
Generating log: systemd | ubuntu-db-04
Lines: 92
GCS URI: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254/04_ubuntu-db-04_systemd.log
```
May 21 10:30:01 ubuntu-db-04 CRON[19801]: (root) CMD (  [ -x /etc/init.d/anacron ] && { cd / && run-parts --report /etc/cron.daily; })
May 21 10:31:15 ubuntu-db-04 systemd-networkd[754]: eth0: Gained carrier
May 21 10:31:15 ubuntu-db-04 systemd-networkd[754]: eth0: DHCPv4 address 10.0.4.54/24 via 10.0.4.1
May 21 10:32:04 ubuntu-db-04 systemd[1]: Starting LVM2 metadata daemon...
May 21 10:32:05 ubuntu-db-04 systemd[1]: Started LVM2 metadata daemon.
May 21 10:33:41 ubuntu-db-04 sshd[19912]: Accepted publickey for admin-user from 10.0.1.100 port 55182 ssh2: RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
May 21 10:33:42 ubuntu-db-04 systemd[1]: Created slice User Slice of UID 1001.
May 21 10:33:42 ubuntu-db-04 systemd[1]: Starting User Runtime Directory /run/user/1001...
May 21 10:33:42 ub
====================================================================================================
Generating log: network | ubuntu-edge-05
Lines: 107
GCS URI: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254/05_ubuntu-edge-05_network.log
```log
Jun 10 14:20:01 ubuntu-edge-05 systemd[1]: Starting Daily apt download activities...
Jun 10 14:20:02 ubuntu-edge-05 systemd[1]: Started Daily apt download activities.
Jun 10 14:20:15 ubuntu-edge-05 chronyd[1052]: Selected source 162.159.200.123 (ntp.ubuntu.com)
Jun 10 14:20:21 ubuntu-edge-05 CRON[12551]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun 10 14:20:33 ubuntu-edge-05 systemd[1]: systemd-hostnamed.service: Succeeded.
Jun 10 14:21:01 ubuntu-edge-05 CRON[12577]: (root) CMD ( /usr/lib/apt/apt.systemd.daily)
Jun 10 14:21:10 ubuntu-edge-05 sshd[12590]: Accepted publickey for user admin from 10.0.1.100 port 54212 ssh2: RSA SHA256:xxxxxxxxxxxxxxxxxx
Jun 10 14:21:10 ubuntu-edge-05 systemd[1]: Created slice User Slice of UID 1000.
Jun 10 14:21:10 ubuntu-edge-05 syst

In [14]:
knowledge_specs = [
    {
        "document_number": 1,
        "document_type": "runbook",
        "topic": "disk_pressure",
        "title": "Ubuntu Disk Pressure and Journal Cleanup Runbook",
        "focus": "journalctl disk usage, apt cache cleanup, log rotation, safe disk investigation",
    },
    {
        "document_number": 2,
        "document_type": "runbook",
        "topic": "systemd_failures",
        "title": "Systemd Service Failure and Restart Loop Runbook",
        "focus": "systemctl status, journalctl -u, restart policy, config validation, rollback",
    },
    {
        "document_number": 3,
        "document_type": "runbook",
        "topic": "ssh_auth_anomaly",
        "title": "SSH Authentication Anomaly Investigation Runbook",
        "focus": "failed login attempts, auth.log inspection, sshd config, fail2ban, account review",
    },
    {
        "document_number": 4,
        "document_type": "runbook",
        "topic": "kernel_driver_warnings",
        "title": "Kernel Driver Warning and Device Reset Runbook",
        "focus": "dmesg analysis, driver timeouts, PCIe reset, kernel module checks, firmware",
    },
    {
        "document_number": 5,
        "document_type": "runbook",
        "topic": "network_instability",
        "title": "Ubuntu Network Instability and DNS Troubleshooting Runbook",
        "focus": "NetworkManager logs, DNS resolution, route inspection, packet loss, interface flaps",
    },
]

pd.DataFrame(knowledge_specs)

,document_number,document_type,topic,title,focus
0,1,runbook,disk_pressure,Ubuntu Disk Pressure and Journal Cleanup Runbook,"journalctl disk usage, apt cache cleanup, log ..."
1,2,runbook,systemd_failures,Systemd Service Failure and Restart Loop Runbook,"systemctl status, journalctl -u, restart polic..."
2,3,runbook,ssh_auth_anomaly,SSH Authentication Anomaly Investigation Runbook,"failed login attempts, auth.log inspection, ss..."
3,4,runbook,kernel_driver_warnings,Kernel Driver Warning and Device Reset Runbook,"dmesg analysis, driver timeouts, PCIe reset, k..."
4,5,runbook,network_instability,Ubuntu Network Instability and DNS Troubleshoo...,"NetworkManager logs, DNS resolution, route ins..."

In [15]:
def generate_knowledge_document(spec: dict) -> str:
    prompt = f"""
You are a senior Linux SRE writing internal Ubuntu troubleshooting documentation.

Brief:
{ubuntu_auditor_brief}

Document specification:
{json.dumps(spec, indent=2, ensure_ascii=False)}

Write a realistic internal runbook in English with these sections:
1. Problem overview
2. Common log patterns
3. First diagnostic commands
4. Risk assessment
5. Safe mitigation options
6. Commands to avoid unless approved
7. Escalation criteria
8. Example Bash helper script

Requirements:
- Keep it practical for Ubuntu.
- Include concrete command examples.
- Do not include destructive commands like rm -rf.
- Prefer safe inspection commands first.
- Include enough text to split into chunks.
- Do not mention that this is AI-generated.
"""

    response = google_vertex_client.models.generate_content(
        model=PLANNING_MODEL,
        contents=prompt,
    )

    return response.text.strip()

In [16]:
knowledge_documents = []

for spec in knowledge_specs:
    print("=" * 100)
    print("Generating knowledge document:", spec["title"])

    content = generate_knowledge_document(spec)

    document = {
        "document_id": str(uuid4()),
        "document_number": spec["document_number"],
        "document_type": spec["document_type"],
        "topic": spec["topic"],
        "title": spec["title"],
        "content": content,
        "summary": content[:700],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    knowledge_documents.append(document)

    print("Characters:", len(content))
    print(content[:700])

====================================================================================================
Generating knowledge document: Ubuntu Disk Pressure and Journal Cleanup Runbook
Characters: 11062
```json
{
  "document_number": 1,
  "document_type": "runbook",
  "topic": "disk_pressure",
  "title": "Ubuntu Disk Pressure and Journal Cleanup Runbook",
  "focus": "journalctl disk usage, apt cache cleanup, log rotation, safe disk investigation"
}
```

---

### **1. Problem Overview**

This runbook addresses alerts related to disk pressure on Ubuntu servers, with a specific focus on issues originating from log accumulation, particularly `systemd-journald`. When a filesystem, especially the root partition (`/`) or `/var`, approaches full capacity, system stability is compromised.

Symptoms manifest as:
*   Application failures with "No space left on device" errors.
*   Inability to write ne
====================================================================================================
Generating knowledge document: Systemd Service Failure and Restart Loop Runbook
Characters: 12626
```json
{
  "document_number": 2,
  "document_type": "runbook",
  "topic": "systemd_failures",
  "title": "Systemd Service Failure and Restart Loop Runbook",
  "focus": "systemctl status, journalctl -u, restart policy, config validation, rollback"
}
```

### 1. Problem Overview

This runbook addresses a common operational issue: a systemd service that is failing to start or is stuck in a crash-restart loop. This is typically observed on services configured with a restart policy such as `Restart=on-failure` or `Restart=always`.

When a service enters this state, it can lead to several negative consequences:
*   **Service Unavailability:** The application or function provided by the service is
====================================================================================================
Generating knowledge document: SSH Authentication Anomaly Investigation Runbook
Characters: 13957
```json
{
  "document_number": 3,
  "document_type": "runbook",
  "topic": "ssh_auth_anomaly",
  "title": "SSH Authentication Anomaly Investigation Runbook",
  "focus": "failed login attempts, auth.log inspection, sshd config, fail2ban, account review"
}
```

### 1. Problem Overview

This runbook provides diagnostic and mitigation steps for SSH authentication anomalies on Ubuntu servers within our cloud environment. An anomaly is defined as a significant deviation from baseline SSH login activity, typically manifesting as a spike in failed authentication attempts.

These events can indicate several scenarios:
*   **Brute-Force Attack:** An automated attempt by external actors to guess user p
====================================================================================================
Generating knowledge document: Kernel Driver Warning and Device Reset Runbook
Characters: 11716
```json
{
  "document_number": 4,
  "document_type": "runbook",
  "topic": "kernel_driver_warnings",
  "title": "Kernel Driver Warning and Device Reset Runbook",
  "focus": "dmesg analysis, driver timeouts, PCIe reset, kernel module checks, firmware"
}
```

### 1. Problem Overview

This runbook addresses alerts triggered by kernel driver warnings, timeouts, or unexpected device resets, typically observed in `dmesg` logs. These events indicate that a kernel module responsible for managing a piece of hardware (e.g., a network card, storage controller, or GPU) is encountering errors.

The impact can range from negligible performance degradation to a complete loss of device functionality, potent
====================================================================================================
Generating knowledge document: Ubuntu Network Instability and DNS Troubleshooting Runbook
Characters: 10490
```json
{
  "document_number": 5,
  "document_type": "runbook",
  "topic": "network_instability",
  "title": "Ubuntu Network Instability and DNS Troubleshooting Runbook",
  "focus": "NetworkManager logs, DNS resolution, route inspection, packet loss, interface flaps"
}
```

### 1. Problem Overview

Network instability on an Ubuntu server can manifest as intermittent packet loss, high latency, complete connectivity loss, or failures in service-to-service communication. This runbook focuses on diagnosing and mitigating network issues at the host level, particularly those related to `NetworkManager`, `systemd-resolved`, interface configuration, and routing.

The primary goal is to methodically

In [17]:
logs_df = pd.DataFrame(
    [
        {
            "log_number": log["log_number"],
            "log_type": log["log_type"],
            "host_name": log["host_name"],
            "scenario": log["scenario"],
            "severity_hint": log["severity_hint"],
            "line_count": len(log["content"].splitlines()),
            "gcs_uri": log["gcs_uri"],
        }
        for log in generated_logs
    ]
)

documents_df = pd.DataFrame(
    [
        {
            "document_number": doc["document_number"],
            "document_type": doc["document_type"],
            "topic": doc["topic"],
            "title": doc["title"],
            "content_length": len(doc["content"]),
        }
        for doc in knowledge_documents
    ]
)

display(logs_df)
display(documents_df)

,log_number,log_type,host_name,scenario,severity_hint,line_count,gcs_uri
0,1,syslog,ubuntu-worker-01,disk pressure and journal growth causing servi...,high,103,gs://leafy-guide-497515-m4-vector-assets/ubunt...
1,2,dmesg,ubuntu-gpu-node-02,kernel driver warnings and intermittent device...,medium,124,gs://leafy-guide-497515-m4-vector-assets/ubunt...
2,3,authlog,ubuntu-api-03,SSH authentication anomaly with repeated faile...,critical,99,gs://leafy-guide-497515-m4-vector-assets/ubunt...
3,4,systemd,ubuntu-db-04,database service restart loop after configurat...,high,92,gs://leafy-guide-497515-m4-vector-assets/ubunt...
4,5,network,ubuntu-edge-05,network instability with DNS failures and inte...,medium,107,gs://leafy-guide-497515-m4-vector-assets/ubunt...

,document_number,document_type,topic,title,content_length
0,1,runbook,disk_pressure,Ubuntu Disk Pressure and Journal Cleanup Runbook,11062
1,2,runbook,systemd_failures,Systemd Service Failure and Restart Loop Runbook,12626
2,3,runbook,ssh_auth_anomaly,SSH Authentication Anomaly Investigation Runbook,13957
3,4,runbook,kernel_driver_warnings,Kernel Driver Warning and Device Reset Runbook,11716
4,5,runbook,network_instability,Ubuntu Network Instability and DNS Troubleshoo...,10490

In [18]:
def normalize_text(text: str) -> str:
    return " ".join(text.split())


def split_text_into_chunks(
    text: str,
    *,
    chunk_size_chars: int = CHUNK_SIZE_CHARS,
    chunk_overlap_chars: int = CHUNK_OVERLAP_CHARS,
) -> list[str]:
    clean_text = normalize_text(text)

    if len(clean_text) <= chunk_size_chars:
        return [clean_text]

    chunks = []
    start = 0

    while start < len(clean_text):
        end = min(start + chunk_size_chars, len(clean_text))

        if end < len(clean_text):
            sentence_boundary = clean_text.rfind(". ", start, end)

            if sentence_boundary > start + int(chunk_size_chars * 0.6):
                end = sentence_boundary + 1

        chunk = clean_text[start:end].strip()

        if chunk:
            chunks.append(chunk)

        if end >= len(clean_text):
            break

        start = max(0, end - chunk_overlap_chars)

    return chunks

In [19]:
def normalize_text(text: str) -> str:
    return " ".join(text.split())


def split_text_into_chunks(
    text: str,
    *,
    chunk_size_chars: int = CHUNK_SIZE_CHARS,
    chunk_overlap_chars: int = CHUNK_OVERLAP_CHARS,
) -> list[str]:
    clean_text = normalize_text(text)

    if len(clean_text) <= chunk_size_chars:
        return [clean_text]

    chunks = []
    start = 0

    while start < len(clean_text):
        end = min(start + chunk_size_chars, len(clean_text))

        if end < len(clean_text):
            sentence_boundary = clean_text.rfind(". ", start, end)

            if sentence_boundary > start + int(chunk_size_chars * 0.6):
                end = sentence_boundary + 1

        chunk = clean_text[start:end].strip()

        if chunk:
            chunks.append(chunk)

        if end >= len(clean_text):
            break

        start = max(0, end - chunk_overlap_chars)

    return chunks

In [20]:
def shorten_text_for_embedding(
    text: str,
    *,
    max_chars: int = MAX_EMBEDDING_TEXT_CHARS,
) -> str:
    clean_text = normalize_text(text)

    if len(clean_text) <= max_chars:
        return clean_text

    return clean_text[:max_chars].rsplit(" ", 1)[0]


def get_text_embedding(text: str) -> list[float]:
    safe_text = shorten_text_for_embedding(text)

    embeddings = text_embedding_model.get_embeddings(
        [safe_text]
    )

    return list(embeddings[0].values)

In [22]:
chunk_rows_without_embeddings = []
global_chunk_number = 1

for log in generated_logs:
    chunks = split_text_into_chunks(log["content"])

    print("=" * 100)
    print("Log:", log["host_name"], log["log_type"])
    print("Chunks:", len(chunks))

    for chunk_index, chunk_text in enumerate(chunks, start=1):
        chunk_rows_without_embeddings.append(
            {
                "chunk_id": str(uuid4()),
                "source_id": log["log_file_id"],
                "source_kind": "log_file",
                "source_number": log["log_number"],
                "chunk_number": chunk_index,
                "global_chunk_number": global_chunk_number,
                "source_type": log["log_type"],
                "topic": log["scenario"],
                "title": f"{log['host_name']} {log['log_type']} log",
                "chunk_text": chunk_text,
                "chunk_char_count": len(chunk_text),
                "embedding_model": TEXT_EMBEDDING_MODEL,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        )

        global_chunk_number += 1

for document in knowledge_documents:
    chunks = split_text_into_chunks(document["content"])

    print("=" * 100)
    print("Document:", document["title"])
    print("Chunks:", len(chunks))

    for chunk_index, chunk_text in enumerate(chunks, start=1):
        chunk_rows_without_embeddings.append(
            {
                "chunk_id": str(uuid4()),
                "source_id": document["document_id"],
                "source_kind": "knowledge_document",
                "source_number": document["document_number"],
                "chunk_number": chunk_index,
                "global_chunk_number": global_chunk_number,
                "source_type": document["document_type"],
                "topic": document["topic"],
                "title": document["title"],
                "chunk_text": chunk_text,
                "chunk_char_count": len(chunk_text),
                "embedding_model": TEXT_EMBEDDING_MODEL,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        )

        global_chunk_number += 1

print("Total chunks:", len(chunk_rows_without_embeddings))

chunks_preview_df = pd.DataFrame(
    [
        {
            "global_chunk_number": row["global_chunk_number"],
            "source_kind": row["source_kind"],
            "source_type": row["source_type"],
            "topic": row["topic"],
            "chunk_char_count": row["chunk_char_count"],
            "preview": row["chunk_text"][:200],
        }
        for row in chunk_rows_without_embeddings
    ]
)

chunks_preview_df.head(12)

====================================================================================================
Log: ubuntu-worker-01 syslog
Chunks: 15
====================================================================================================
Log: ubuntu-gpu-node-02 dmesg
Chunks: 10
====================================================================================================
Log: ubuntu-api-03 authlog
Chunks: 11
====================================================================================================
Log: ubuntu-db-04 systemd
Chunks: 10
====================================================================================================
Log: ubuntu-edge-05 network
Chunks: 14
====================================================================================================
Document: Ubuntu Disk Pressure and Journal Cleanup Runbook
Chunks: 12
====================================================================================================
Document: Systemd Service Failure and Restart Loop Runbook
Chunks: 14
====================================================================================================
Document: SSH Authentication Anomaly Investigation Runbook
Chunks: 16
====================================================================================================
Document: Kernel Driver Warning and Device Reset Runbook
Chunks: 13
====================================================================================================
Document: Ubuntu Network Instability and DNS Troubleshooting Runbook
Chunks: 11
Total chunks: 126

,global_chunk_number,source_kind,source_type,topic,chunk_char_count,preview
0,1,log_file,syslog,disk pressure and journal growth causing servi...,1191,Oct 26 08:30:01 ubuntu-worker-01 systemd[1]: S...
1,2,log_file,syslog,disk pressure and journal growth causing servi...,1127,32:41 ubuntu-worker-01 systemd[1]: kubelet.ser...
2,3,log_file,syslog,disk pressure and journal growth causing servi...,1103,sult 'exit-code'. Oct 26 08:33:57 ubuntu-worke...
3,4,log_file,syslog,disk pressure and journal growth causing servi...,823,"ask_timeout_secs"" disables this message. Oct 2..."
4,5,log_file,syslog,disk pressure and journal growth causing servi...,879,"ce: Scheduled restart job, restart counter is ..."
5,6,log_file,syslog,disk pressure and journal growth causing servi...,1013,"ce: Scheduled restart job, restart counter is ..."
6,7,log_file,syslog,disk pressure and journal growth causing servi...,1164,"ce: Scheduled restart job, restart counter is ..."
7,8,log_file,syslog,disk pressure and journal growth causing servi...,771,orker-01 systemd[1]: apt-daily-upgrade.service...
8,9,log_file,syslog,disk pressure and journal growth causing servi...,1200,"ce: Scheduled restart job, restart counter is ..."
9,10,log_file,syslog,disk pressure and journal growth causing servi...,865,39:01 ubuntu-worker-01 CRON[23620]: pam_unix(c...
10,11,log_file,syslog,disk pressure and journal growth causing servi...,1052,"ce: Scheduled restart job, restart counter is ..."
11,12,log_file,syslog,disk pressure and journal growth causing servi...,1069,belet/pods/deadbeef-1234-5678-abcd-deadbeef123...

In [23]:
chunk_rows = []

for row in chunk_rows_without_embeddings:
    print(
        "Embedding chunk:",
        row["global_chunk_number"],
        "|",
        row["source_kind"],
        "|",
        row["source_type"],
    )

    embedding = get_text_embedding(row["chunk_text"])

    chunk_rows.append(
        {
            **row,
            "embedding": embedding,
        }
    )

    print("Embedding dim:", len(embedding))
    print("Chunk chars:", row["chunk_char_count"])
    print("-" * 100)

print("Chunk rows with embeddings:", len(chunk_rows))

Embedding chunk: 1 | log_file | syslog
Embedding dim: 768
Chunk chars: 1191
----------------------------------------------------------------------------------------------------
Embedding chunk: 2 | log_file | syslog
Embedding dim: 768
Chunk chars: 1127
----------------------------------------------------------------------------------------------------
Embedding chunk: 3 | log_file | syslog
Embedding dim: 768
Chunk chars: 1103
----------------------------------------------------------------------------------------------------
Embedding chunk: 4 | log_file | syslog
Embedding dim: 768
Chunk chars: 823
----------------------------------------------------------------------------------------------------
Embedding chunk: 5 | log_file | syslog
Embedding dim: 768
Chunk chars: 879
----------------------------------------------------------------------------------------------------
Embedding chunk: 6 | log_file | syslog
Embedding dim: 768
Chunk chars: 1013
----------------------------------------------------------------------------------------------------
Embedding chunk: 7 | log_file | syslog
Embedding dim: 768
Chunk chars: 1164
----------------------------------------------------------------------------------------------------
Embedding chunk: 8 | log_file | syslog
Embedding dim: 768
Chunk chars: 771
----------------------------------------------------------------------------------------------------
Embedding chunk: 9 | log_file | syslog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 10 | log_file | syslog
Embedding dim: 768
Chunk chars: 865
----------------------------------------------------------------------------------------------------
Embedding chunk: 11 | log_file | syslog
Embedding dim: 768
Chunk chars: 1052
----------------------------------------------------------------------------------------------------
Embedding chunk: 12 | log_file | syslog
Embedding dim: 768
Chunk chars: 1069
----------------------------------------------------------------------------------------------------
Embedding chunk: 13 | log_file | syslog
Embedding dim: 768
Chunk chars: 741
----------------------------------------------------------------------------------------------------
Embedding chunk: 14 | log_file | syslog
Embedding dim: 768
Chunk chars: 1137
----------------------------------------------------------------------------------------------------
Embedding chunk: 15 | log_file | syslog
Embedding dim: 768
Chunk chars: 375
----------------------------------------------------------------------------------------------------
Embedding chunk: 16 | log_file | dmesg
Embedding dim: 768
Chunk chars: 879
----------------------------------------------------------------------------------------------------
Embedding chunk: 17 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 18 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 19 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 20 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 21 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 22 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 23 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 24 | log_file | dmesg
Embedding dim: 768
Chunk chars: 790
----------------------------------------------------------------------------------------------------
Embedding chunk: 25 | log_file | dmesg
Embedding dim: 768
Chunk chars: 1018
----------------------------------------------------------------------------------------------------
Embedding chunk: 26 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 27 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 28 | log_file | authlog
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 29 | log_file | authlog
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 30 | log_file | authlog
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 31 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 32 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 33 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 34 | log_file | authlog
Embedding dim: 768
Chunk chars: 970
----------------------------------------------------------------------------------------------------
Embedding chunk: 35 | log_file | authlog
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 36 | log_file | authlog
Embedding dim: 768
Chunk chars: 1001
----------------------------------------------------------------------------------------------------
Embedding chunk: 37 | log_file | systemd
Embedding dim: 768
Chunk chars: 1120
----------------------------------------------------------------------------------------------------
Embedding chunk: 38 | log_file | systemd
Embedding dim: 768
Chunk chars: 1155
----------------------------------------------------------------------------------------------------
Embedding chunk: 39 | log_file | systemd
Embedding dim: 768
Chunk chars: 1118
----------------------------------------------------------------------------------------------------
Embedding chunk: 40 | log_file | systemd
Embedding dim: 768
Chunk chars: 1013
----------------------------------------------------------------------------------------------------
Embedding chunk: 41 | log_file | systemd
Embedding dim: 768
Chunk chars: 1176
----------------------------------------------------------------------------------------------------
Embedding chunk: 42 | log_file | systemd
Embedding dim: 768
Chunk chars: 1131
----------------------------------------------------------------------------------------------------
Embedding chunk: 43 | log_file | systemd
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 44 | log_file | systemd
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 45 | log_file | systemd
Embedding dim: 768
Chunk chars: 1097
----------------------------------------------------------------------------------------------------
Embedding chunk: 46 | log_file | systemd
Embedding dim: 768
Chunk chars: 1020
----------------------------------------------------------------------------------------------------
Embedding chunk: 47 | log_file | network
Embedding dim: 768
Chunk chars: 1109
----------------------------------------------------------------------------------------------------
Embedding chunk: 48 | log_file | network
Embedding dim: 768
Chunk chars: 1022
----------------------------------------------------------------------------------------------------
Embedding chunk: 49 | log_file | network
Embedding dim: 768
Chunk chars: 1041
----------------------------------------------------------------------------------------------------
Embedding chunk: 50 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 51 | log_file | network
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 52 | log_file | network
Embedding dim: 768
Chunk chars: 914
----------------------------------------------------------------------------------------------------
Embedding chunk: 53 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 54 | log_file | network
Embedding dim: 768
Chunk chars: 865
----------------------------------------------------------------------------------------------------
Embedding chunk: 55 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 56 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 57 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 58 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 59 | log_file | network
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 60 | log_file | network
Embedding dim: 768
Chunk chars: 570
----------------------------------------------------------------------------------------------------
Embedding chunk: 61 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1192
----------------------------------------------------------------------------------------------------
Embedding chunk: 62 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1052
----------------------------------------------------------------------------------------------------
Embedding chunk: 63 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 883
----------------------------------------------------------------------------------------------------
Embedding chunk: 64 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1127
----------------------------------------------------------------------------------------------------
Embedding chunk: 65 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1135
----------------------------------------------------------------------------------------------------
Embedding chunk: 66 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1166
----------------------------------------------------------------------------------------------------
Embedding chunk: 67 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1161
----------------------------------------------------------------------------------------------------
Embedding chunk: 68 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1151
----------------------------------------------------------------------------------------------------
Embedding chunk: 69 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1193
----------------------------------------------------------------------------------------------------
Embedding chunk: 70 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 71 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1188
----------------------------------------------------------------------------------------------------
Embedding chunk: 72 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 437
----------------------------------------------------------------------------------------------------
Embedding chunk: 73 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1046
----------------------------------------------------------------------------------------------------
Embedding chunk: 74 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 852
----------------------------------------------------------------------------------------------------
Embedding chunk: 75 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1031
----------------------------------------------------------------------------------------------------
Embedding chunk: 76 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1107
----------------------------------------------------------------------------------------------------
Embedding chunk: 77 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1181
----------------------------------------------------------------------------------------------------
Embedding chunk: 78 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 968
----------------------------------------------------------------------------------------------------
Embedding chunk: 79 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1086
----------------------------------------------------------------------------------------------------
Embedding chunk: 80 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1175
----------------------------------------------------------------------------------------------------
Embedding chunk: 81 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1141
----------------------------------------------------------------------------------------------------
Embedding chunk: 82 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1132
----------------------------------------------------------------------------------------------------
Embedding chunk: 83 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1050
----------------------------------------------------------------------------------------------------
Embedding chunk: 84 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1137
----------------------------------------------------------------------------------------------------
Embedding chunk: 85 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 86 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 712
----------------------------------------------------------------------------------------------------
Embedding chunk: 87 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1044
----------------------------------------------------------------------------------------------------
Embedding chunk: 88 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 967
----------------------------------------------------------------------------------------------------
Embedding chunk: 89 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 934
----------------------------------------------------------------------------------------------------
Embedding chunk: 90 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 998
----------------------------------------------------------------------------------------------------
Embedding chunk: 91 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 837
----------------------------------------------------------------------------------------------------
Embedding chunk: 92 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 93 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1189
----------------------------------------------------------------------------------------------------
Embedding chunk: 94 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1162
----------------------------------------------------------------------------------------------------
Embedding chunk: 95 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1188
----------------------------------------------------------------------------------------------------
Embedding chunk: 96 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1059
----------------------------------------------------------------------------------------------------
Embedding chunk: 97 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1069
----------------------------------------------------------------------------------------------------
Embedding chunk: 98 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1112
----------------------------------------------------------------------------------------------------
Embedding chunk: 99 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 728
----------------------------------------------------------------------------------------------------
Embedding chunk: 100 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 101 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1200
----------------------------------------------------------------------------------------------------
Embedding chunk: 102 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 347
----------------------------------------------------------------------------------------------------
Embedding chunk: 103 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1199
----------------------------------------------------------------------------------------------------
Embedding chunk: 104 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 882
----------------------------------------------------------------------------------------------------
Embedding chunk: 105 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1041
----------------------------------------------------------------------------------------------------
Embedding chunk: 106 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1154
----------------------------------------------------------------------------------------------------
Embedding chunk: 107 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 1172
----------------------------------------------------------------------------------------------------
Embedding chunk: 108 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 961
----------------------------------------------------------------------------------------------------
Embedding chunk: 109 | knowledge_document | runbook
Embedding dim: 768
Chunk chars: 889
----------------------------------------------------------------------------------------------------
Embedding chunk: 110 | knowledge_document | runbook

In [24]:
log_rows = []

for log in generated_logs:
    log_rows.append(
        {
            "log_file_id": log["log_file_id"],
            "log_number": log["log_number"],
            "log_type": log["log_type"],
            "host_name": log["host_name"],
            "scenario": log["scenario"],
            "severity_hint": log["severity_hint"],
            "content": log["content"],
            "gcs_uri": log["gcs_uri"],
            "created_at": log["created_at"],
        }
    )

document_rows = []

for document in knowledge_documents:
    document_rows.append(
        {
            "document_id": document["document_id"],
            "document_number": document["document_number"],
            "document_type": document["document_type"],
            "topic": document["topic"],
            "title": document["title"],
            "content": document["content"],
            "summary": document["summary"],
            "created_at": document["created_at"],
        }
    )

bigquery_client.query(
    f"TRUNCATE TABLE `{log_table_ref}`",
    location=dataset.location,
).result()

bigquery_client.query(
    f"TRUNCATE TABLE `{document_table_ref}`",
    location=dataset.location,
).result()

bigquery_client.query(
    f"TRUNCATE TABLE `{chunk_table_ref}`",
    location=dataset.location,
).result()

log_errors = bigquery_client.insert_rows_json(
    log_table_ref,
    log_rows,
)

document_errors = bigquery_client.insert_rows_json(
    document_table_ref,
    document_rows,
)

chunk_errors = bigquery_client.insert_rows_json(
    chunk_table_ref,
    chunk_rows,
)

if log_errors:
    print("Log insert errors:")
    print(log_errors)
else:
    print("Inserted log rows:", len(log_rows))

if document_errors:
    print("Document insert errors:")
    print(document_errors)
else:
    print("Inserted document rows:", len(document_rows))

if chunk_errors:
    print("Chunk insert errors:")
    print(chunk_errors)
else:
    print("Inserted chunk rows:", len(chunk_rows))

Inserted log rows: 5
Inserted document rows: 5
Inserted chunk rows: 126

In [25]:
sql = f"""
SELECT
  (SELECT COUNT(*) FROM `{log_table_ref}`) AS log_count,
  (SELECT COUNT(*) FROM `{document_table_ref}`) AS document_count,
  (SELECT COUNT(*) FROM `{chunk_table_ref}`) AS chunk_count,
  (
    SELECT ARRAY_LENGTH(embedding)
    FROM `{chunk_table_ref}`
    LIMIT 1
  ) AS embedding_length
"""

result = list(
    bigquery_client.query(
        sql,
        location=dataset.location,
    )
)[0]

print("Log count:", result.log_count)
print("Document count:", result.document_count)
print("Chunk count:", result.chunk_count)
print("Embedding length:", result.embedding_length)

Log count: 5
Document count: 5
Chunk count: 126
Embedding length: 768

In [26]:
def search_ubuntu_chunks(
    query: str,
    *,
    top_k: int = 10,
    source_kind: str | None = None,
    source_type: str | None = None,
) -> list[dict]:
    query_embedding = get_text_embedding(query)

    filters = []

    query_parameters = [
        bigquery.ArrayQueryParameter(
            "query_embedding",
            "FLOAT64",
            query_embedding,
        ),
        bigquery.ScalarQueryParameter(
            "top_k",
            "INT64",
            top_k,
        ),
    ]

    if source_kind is not None:
        filters.append("source_kind = @source_kind")
        query_parameters.append(
            bigquery.ScalarQueryParameter(
                "source_kind",
                "STRING",
                source_kind,
            )
        )

    if source_type is not None:
        filters.append("source_type = @source_type")
        query_parameters.append(
            bigquery.ScalarQueryParameter(
                "source_type",
                "STRING",
                source_type,
            )
        )

    where_sql = ""

    if filters:
        where_sql = "WHERE " + " AND ".join(filters)

    sql = f"""
    SELECT
      base.chunk_id,
      base.source_id,
      base.source_kind,
      base.source_number,
      base.chunk_number,
      base.global_chunk_number,
      base.source_type,
      base.topic,
      base.title,
      base.chunk_text,
      distance
    FROM VECTOR_SEARCH(
      (
        SELECT *
        FROM `{chunk_table_ref}`
        {where_sql}
      ),
      'embedding',
      (SELECT @query_embedding AS embedding),
      top_k => @top_k,
      distance_type => 'COSINE'
    )
    ORDER BY distance ASC
    """

    job_config = bigquery.QueryJobConfig(
        query_parameters=query_parameters,
    )

    query_job = bigquery_client.query(
        sql,
        job_config=job_config,
        location=dataset.location,
    )

    return [
        {
            "chunk_id": row.chunk_id,
            "source_id": row.source_id,
            "source_kind": row.source_kind,
            "source_number": row.source_number,
            "chunk_number": row.chunk_number,
            "global_chunk_number": row.global_chunk_number,
            "source_type": row.source_type,
            "topic": row.topic,
            "title": row.title,
            "chunk_text": row.chunk_text,
            "distance": row.distance,
        }
        for row in query_job
    ]

In [27]:
query = """
Ubuntu server has low disk space, systemd services are restarting,
journal logs are growing, and apt cache may be consuming space.
What should be inspected first?
"""

search_results = search_ubuntu_chunks(
    query,
    top_k=10,
)

print("Query:")
print(query)

print("\nSearch results:", len(search_results))

for result in search_results:
    print("=" * 100)
    print("Distance:", round(result["distance"], 4))
    print("Source kind:", result["source_kind"])
    print("Source type:", result["source_type"])
    print("Topic:", result["topic"])
    print("Title:", result["title"])
    print("Global chunk:", result["global_chunk_number"])
    print(result["chunk_text"][:900])

Query:

Ubuntu server has low disk space, systemd services are restarting,
journal logs are growing, and apt cache may be consuming space.
What should be inspected first?


Search results: 10
====================================================================================================
Distance: 0.1862
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 61
```json { "document_number": 1, "document_type": "runbook", "topic": "disk_pressure", "title": "Ubuntu Disk Pressure and Journal Cleanup Runbook", "focus": "journalctl disk usage, apt cache cleanup, log rotation, safe disk investigation" } ``` --- ### **1. Problem Overview** This runbook addresses alerts related to disk pressure on Ubuntu servers, with a specific focus on issues originating from log accumulation, particularly `systemd-journald`. When a filesystem, especially the root partition (`/`) or `/var`, approaches full capacity, system stability is compromised. Symptoms manifest as: * Application failures with "No space left on device" errors. * Inability to write new log entries, blinding monitoring systems. * Performance degradation due to filesystem overhead. * In severe cases, the filesystem may be remounted as read-only by the kernel to prevent corruption, leading to a hard-d
====================================================================================================
Distance: 0.2041
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 62
naway log generation, bloated package manager caches (`apt`), unrotated application logs, and large temporary files. This guide prioritizes safe, non-destructive investigation and mitigation. ### **2. Common Log Patterns** Our central log auditor will typically flag one or more of the following patterns when this issue occurs. These snippets are retrieved from our BigQuery log storage. **Pattern: systemd-journald approaching its size limit** This is a direct warning that the system journal is consuming a significant and configured amount of disk space. It's a proactive warning before space is completely exhausted. ```log { "timestamp": "2023-10-27T10:30:01.123456Z", "hostname": "prod-app-server-04", "process": "systemd-journald", "message": "System Journal (/var/log/journal/a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6) is 8.0G, nearing maximum limit of 8.0G (99.9% used)." } ``` **Pattern: Kernel det
====================================================================================================
Distance: 0.2212
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 67
safe and are the first line of defense. They use built-in system tools to manage data correctly. 1. **Clean the Systemd Journal:** This is the preferred method for reducing journald's disk footprint. It's safer than `rm` because it correctly handles the journal's database format. * **Vacuum by size:** Reduce the journal size to a specific target (e.g., 500MB). ```bash sudo journalctl --vacuum-size=500M ``` * **Vacuum by time:** Remove all journal entries older than a specified time (e.g., 2 days). ```bash sudo journalctl --vacuum-time=2d ``` 2. **Clean APT Cache:** Safely remove cached package files (`.deb`) that are no longer needed. This can often free up several gigabytes in `/var/cache/apt/`. ```bash sudo apt-get clean ``` 3. **Force Log Rotation:** If you have identified large, unrotated text logs (e.g., in `/var/log/nginx`), you can manually trigger a rotation cycle. This will rena
====================================================================================================
Distance: 0.2241
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 68
e rules in `/etc/logrotate.d/`. ```bash sudo logrotate -f /etc/logrotate.conf ``` 4. **Clean Up Old Snap Packages (if applicable):** Snapd can keep multiple old revisions of packages, consuming space. ```bash # This script removes all but the active revision of each snap. snap list --all | awk '/disabled/{print $1, $3}' | while read snapname revision; do sudo snap remove "$snapname" --revision="$revision"; done ``` 5. **Restart Service Holding Deleted File:** If `lsof +L1` identified a process holding a large, deleted file, gracefully restarting that service will release the file handle and free the disk space. ```bash sudo systemctl restart <service-name> ``` ### **6. Commands to Avoid Unless Approved** **Under no circumstances should these commands be run during initial triage.** They carry a high risk of making the situation worse, causing data loss, or breaking system functionality.
====================================================================================================
Distance: 0.2347
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 64
filesystem read-only" } ``` **Pattern: Application or system service failure** A generic but clear indicator that a write operation has failed. This is often the first symptom seen by service owners. ```log { "timestamp": "2023-10-27T10:55:00.456789Z", "hostname": "prod-app-server-04", "process": "nginx", "message": "open() \"/var/log/nginx/access.log\" failed (28: No space left on device)" } ``` **Pattern: APT package manager failure** This indicates the `/var/cache` partition is full, preventing system patches or package installations. ```log { "timestamp": "2023-10-27T09:00:10.123Z", "hostname": "prod-app-server-04", "process": "apt-get", "message": "E: You don't have enough free space in /var/cache/apt/archives/." } ``` ### **3. First Diagnostic Commands** Once connected to the affected instance, run these read-only commands to assess the situation. **Do not perform any write or dele
====================================================================================================
Distance: 0.2381
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 65
.** 1. **Check Filesystem Usage:** Get a human-readable overview of all mounted filesystems. Pay close attention to the `Use%` on `/`, `/var`, and any application-specific mounts. ```bash df -h ``` 2. **Identify Largest Directories:** Find the top-level directories consuming the most space. Start with `/var` as it's the most common location for log and cache growth. The `du` command can be slow on large filesystems. ```bash # Check top 10 largest subdirectories in /var du -shc /var/* | sort -rh | head -10 ``` 3. **Check Inode Usage:** In rare cases, the disk may be full due to inode exhaustion (millions of tiny files) rather than raw data volume. ```bash df -i ``` 4. **Inspect Journald Disk Usage:** Use the `journalctl` utility to confirm how much space the systemd journal is actually using on disk. ```bash journalctl --disk-usage ``` 5. **Find Open File Handles for Deleted Files:** Some
====================================================================================================
Distance: 0.2433
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 71
might not be world-readable sudo du -shc /var/* | sort -rh | head -10 echo "" echo "=> Systemd Journal Disk Usage (journalctl --disk-usage):" sudo journalctl --disk-usage echo "" # --- Phase 2: Proposed Mitigation & Confirmation --- echo "--- [Phase 2: Proposed Mitigation] ---" echo "The script will perform the following SAFE cleanup operations:" echo " 1. Clean apt cache (sudo apt-get clean)" echo " 2. Vacuum systemd journal to a max size of 500M (sudo journalctl --vacuum-size=500M)" echo " 3. Force rotation of all logs managed by logrotate (sudo logrotate -f /etc/logrotate.conf)" echo "" read -p "Do you want to proceed with the cleanup? (y/n) " -n 1 -r echo "" if [[ ! $REPLY =~ ^[Yy]$ ]]; then echo "Cleanup aborted by user." exit 1 fi # --- Phase 3: Execution --- echo "" echo "--- [Phase 3: Executing Cleanup] ---" echo "=> Cleaning apt cache..." sudo apt-get clean echo "Done." echo ""
====================================================================================================
Distance: 0.26
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 66
a process still holds it open, preventing the space from being freed. `lsof` can identify these. ```bash # This command lists files that have been deleted but are still held open lsof +L1 ``` ### **4. Risk Assessment** * **HIGH:** The filesystem has been remounted read-only (`ro`). Critical services are down. This is a production outage and requires immediate, careful intervention. The primary risk is exacerbating the problem by running incorrect commands. * **MEDIUM:** Disk usage is > 95%. Applications are reporting "No space left" errors, but the core OS is still functional. Service degradation is occurring. There is a high risk of escalation to a `HIGH` state if not addressed promptly. * **LOW:** Disk usage is > 85% and an alert has been triggered proactively. No services are reporting errors yet. This is the ideal time to intervene, as the risk of causing a further incident is minima
====================================================================================================
Distance: 0.2635
Source kind: knowledge_document
Source type: runbook
Topic: disk_pressure
Title: Ubuntu Disk Pressure and Journal Cleanup Runbook
Global chunk: 72
cho "" echo "=> Forcing log rotation..." sudo logrotate -f /etc/logrotate.conf echo "Done." echo "" # --- Phase 4: Post-Action Report --- echo "--- [Phase 4: Final Report] ---" echo "Cleanup complete. Verifying new disk space..." echo "" echo "=> New Filesystem Usage (df -h):" df -h echo "" echo "=> New Systemd Journal Disk Usage (journalctl --disk-usage):" sudo journalctl --disk-usage echo "" echo "Script finished successfully." ```
====================================================================================================
Distance: 0.2755
Source kind: log_file
Source type: syslog
Topic: disk pressure and journal growth causing service instability
Title: ubuntu-worker-01 syslog log
Global chunk: 9
ce: Scheduled restart job, restart counter is at 6. Oct 26 08:38:46 ubuntu-worker-01 systemd[1]: Stopped Kubernetes Kubelet. Oct 26 08:38:46 ubuntu-worker-01 systemd[1]: Starting Kubernetes Kubelet... Oct 26 08:38:47 ubuntu-worker-01 kernel: [ 7632.987654] EXT4-fs (sda1): failing file system due to no space left on device Oct 26 08:38:47 ubuntu-worker-01 kubelet[23601]: E1026 08:38:47.123987 23601 writer.go:108] "Failed to write checkpoint" err="failed to write checkpoint object to disk: write /var/lib/kubelet/kubeadm-flags.env.checkpoint2108882987: no space left on device" Oct 26 08:38:47 ubuntu-worker-01 systemd-journald[489]: Failed to write entry (22 items, 638 bytes), ignoring: No space left on device Oct 26 08:38:48 ubuntu-worker-01 systemd[1]: snapd.service: Failed to run serializer: No space left on device Oct 26 08:39:01 ubuntu-worker-01 CRON[23620]: (root) CMD ( [ -x /usr/lib/p

In [28]:
def build_ubuntu_rag_context(results: list[dict]) -> str:
    parts = []

    for index, result in enumerate(results, start=1):
        parts.append(
            "\n".join(
                [
                    f"[SOURCE {index}]",
                    f"Chunk ID: {result['chunk_id']}",
                    f"Source kind: {result['source_kind']}",
                    f"Source type: {result['source_type']}",
                    f"Title: {result['title']}",
                    f"Topic: {result['topic']}",
                    f"Global chunk number: {result['global_chunk_number']}",
                    f"Distance: {result['distance']:.4f}",
                    f"Chunk text: {result['chunk_text']}",
                ]
            )
        )

    return "\n\n---\n\n".join(parts)

In [29]:
def audit_ubuntu_issue(
    question: str,
    *,
    top_k: int = 12,
) -> dict:
    results = search_ubuntu_chunks(
        question,
        top_k=top_k,
    )

    context = build_ubuntu_rag_context(results)

    prompt = f"""
You are a senior Ubuntu SRE and security-aware log auditor.

Analyze the issue using only the retrieved log chunks and knowledge chunks.

Question:
{question}

Retrieved chunks:
{context}

Return a practical audit report with:
1. Executive summary
2. Most likely primary issue
3. Evidence from log chunks
4. Relevant knowledge-base guidance
5. Operational risk level: low, medium, high, or critical
6. First diagnostic commands
7. Safe mitigation plan
8. Commands to avoid
9. Escalation criteria
10. Sources used, referencing SOURCE numbers

Rules:
- Stay grounded in retrieved chunks.
- Do not invent evidence.
- Prefer non-destructive diagnostics.
- Do not include destructive commands.
- If evidence is insufficient, say what is missing.
"""

    response = google_vertex_client.models.generate_content(
        model=TEXT_MODEL,
        contents=prompt,
    )

    return {
        "question": question,
        "answer": response.text,
        "search_results": results,
        "rag_context": context,
    }

In [30]:
audit_question = """
The Ubuntu worker server is unstable. Services restart repeatedly,
disk usage is close to full, journal logs appear large, and there are apt cache warnings.
Audit the issue and recommend safe diagnostics and mitigation.
"""

ubuntu_audit_result = audit_ubuntu_issue(
    audit_question,
    top_k=12,
)

print("AUDIT QUESTION:")
print(ubuntu_audit_result["question"])

print("\nAUDIT REPORT:")
print(ubuntu_audit_result["answer"])

AUDIT QUESTION:

The Ubuntu worker server is unstable. Services restart repeatedly,
disk usage is close to full, journal logs appear large, and there are apt cache warnings.
Audit the issue and recommend safe diagnostics and mitigation.


AUDIT REPORT:
Here is an audit report for the unstable Ubuntu worker server:

### 1. Executive Summary

The Ubuntu worker server `ubuntu-worker-01` is experiencing critical instability due to severe disk pressure. Multiple services, including Kubernetes Kubelet, systemd-journald, apt, and snapd, are failing to write data, leading to repeated restarts and service unavailability. The root cause is a "No space left on device" condition on the primary filesystem, exacerbated by large journal logs and apt cache issues.

### 2. Most Likely Primary Issue

The primary issue is a **critical "No space left on device" condition** on the root filesystem (likely `/` or `/var`), leading to cascading service failures and instability. This is directly causing services to crash, fail to start, and enter restart loops, as well as preventing system logging and package management operations.

### 3. Evidence from Log Chunks

The following log entries confirm the disk pressure and its impact:

*   **"No space left on device" errors:**
    *   `Oct 26 08:38:47 ubuntu-worker-01 kernel: [ 7632.987654] EXT4-fs (sda1): failing file system due to no space left on device` (SOURCE 4)
    *   `Oct 26 08:38:47 ubuntu-worker-01 kubelet[23601]: E1026 08:38:47.123987 23601 writer.go:108] "Failed to write checkpoint" err="failed to write checkpoint object to disk: write /var/lib/kubelet/kubeadm-flags.env.checkpoint2108882987: no space left on device"` (SOURCE 4)
    *   `Oct 26 08:38:47 ubuntu-worker-01 systemd-journald[489]: Failed to write entry (22 items, 638 bytes), ignoring: No space left on device` (SOURCE 4)
    *   `Oct 26 08:38:48 ubuntu-worker-01 systemd[1]: snapd.service: Failed to run serializer: No space left on device` (SOURCE 4)
    *   `Oct 26 08:37:50 ubuntu-worker-01 systemd-logind[678]: Failed to write session file: No space left on device` (SOURCE 5)
    *   `Oct 26 08:37:56 ubuntu-worker-01 apt.systemd.daily[23530]: E:Could not open lock file /var/lib/dpkg/lock-frontend - open (28: No space left on device)` (SOURCE 5)
    *   `Oct 26 08:41:01 ubuntu-worker-01 kubelet[23750]: Error: failed to run Kubelet: failed to create kubelet class resources: failed to create diskperformance profile: failed to create new perf recorder: failed to create directory "/sys/fs/cgroup/perf_event/kubepods/burstable/besteffort.slice": mkdir /sys/fs/cgroup/perf_event/kubepods/burstable/besteffort.slice: no space left on device` (SOURCE 10)

*   **Journal Log Growth and Failure:**
    *   `Oct 26 08:35:05 ubuntu-worker-01 systemd-journald[489]: Journal file /var/log/journal/a1b2c3d4/system.journal is nearing maximum size (95.0M of 100.0M).` (SOURCE 9)
    *   `Oct 26 08:41:00 ubuntu-worker-01 systemd-journald[489]: /var/log/journal/a1b2c3d4/system.journal: Journal file rotation timed out or failed: No space left on device` (SOURCE 10)

*   **Repeated Service Restarts (Kubelet):**
    *   `Oct 26 08:35:08 ubuntu-worker-01 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION` (SOURCE 9)
    *   `Oct 26 08:35:13 ubuntu-worker-01 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 3.` (SOURCE 9)
    *   `Oct 26 08:37:35 ubuntu-worker-01 systemd[1]: Starting Kubernetes Kubelet...` (SOURCE 5)
    *   `Oct 26 08:41:01 ubuntu-worker-01 systemd[1]: kubelet.service: Failed with result 'exit-code'.` (SOURCE 10)
    *   `Oct 26 08:41:05 ubuntu-worker-01 systemd[1]: kubelet.service: Start request repeated too quickly.` (SOURCE 10)

### 4. Relevant Knowledge-base Guidance

*   **Problem Overview:** SOURCE 1 and SOURCE 2 describe disk pressure as a critical issue leading to "No space left on device" errors, application failures, performance degradation, and potential kernel-forced read-only remounts. Common culprits include runaway log generation (e.g., `systemd-journald`) and bloated package manager caches (`apt`).
*   **Log Patterns:** The logs match several patterns outlined in the runbook:
    *   `systemd-journald approaching its size limit` (SOURCE 2, seen in SOURCE 9).
    *   `Application or system service failure` with "No space left on device" (SOURCE 3, seen across multiple services).
    *   `APT package manager failure` (SOURCE 3, seen in SOURCE 5).
*   **Safe Mitigation Options:** The runbook explicitly details safe methods for cleaning up `apt` cache and `systemd-journald` logs (SOURCE 6).

### 5. Operational Risk Level

**HIGH**

The system is exhibiting widespread "No space left on device" errors affecting critical services like Kubelet and even systemd-journald itself, preventing logging and log rotation. The kernel is explicitly reporting `EXT4-fs (sda1): failing file system due to no space left on device`. While a full "remounting filesystem read-only" message isn't explicitly in the provided logs (which would make it CRITICAL), the current state is severe enough that a full system stall or read-only transition is imminent or already partially occurring for write operations. Services are repeatedly failing to start, leading to a loss of functionality on the worker node. (References: SOURCE 1, SOURCE 12).

### 6. First Diagnostic Commands

These commands are read-only and will help confirm the disk usage and identify specific culprits without risk:

1.  **Check Filesystem Usage:** Get a human-readable overview of all mounted filesystems, especially `/` and `/var`.
    ```bash
    df -h
    ```
    (Reference: SOURCE 3)
2.  **Identify Large Directories:** Find the top 10 largest directories within `/var`. Adjust path as needed based on `df -h` output.
    ```bash
    sudo du -shc /var/* | sort -rh | head -10
    ```
    (Reference: SOURCE 6)
3.  **Check Systemd Journal Disk Usage:** Determine how much space `journald` is consuming.
    ```bash
    sudo journalctl --disk-usage
    ```
    (Reference: SOURCE 6)
4.  **Check for Deleted Files Still Held Open:** Identify any deleted files that are still held open by processes, preventing space reclamation.
    ```bash
    sudo lsof +L1
    ```
    (Reference: SOURCE 12)

### 7. Safe Mitigation Plan

Based on the evidence, the primary targets for cleanup are the `apt` cache and `systemd-journald` logs.

1.  **Clean apt cache:**
    ```bash
    sudo apt-get clean
    ```
    (Reference: SOURCE 6)
2.  **Vacuum systemd journal:** Limit the total size of the journal. A value like `500M` is a reasonable starting point to free up space quickly.
    ```bash
    sudo journalctl --vacuum-size=500M
    ```
    (Reference: SOURCE 6)
3.  **Force Log Rotation:** Ensure all configured log files are rotated, which might move older logs or compress them if configured.
    ```bash
    sudo logrotate -f /etc/logrotate.conf
    ```
    (Reference: SOURCE 6)
4.  **Post-Mitigation Check:** After performing the above steps, re-run `df -h` to confirm that disk space has been freed.
    ```bash
    df -h
    ```
    (Reference: SOURCE 3)
5.  **Monitor Services:** Check if critical services like Kubelet stabilize and stop restarting.

### 8. Commands to Avoid

*   **Directly deleting log files:** Never use `rm` on active log files or journal directories.
    *   `rm -rf /var/log/*`
    *   `rm -f /var/log/journal/*`
    *   **Reason:** This can corrupt the journal database, break processes that have logs open, and potentially lead to data loss or further system instability. Use `journalctl --vacuum-*` and `logrotate` instead.
    (Reference: SOURCE 8)

### 9. Escalation Criteria

*   If the filesystem is found to be remounted read-only (`ro`) during diagnostics (e.g., via `mount` command).
*   If the safe mitigation steps fail to free significant disk space or stabilize the services within 15-30 minutes.
*   If critical Kubernetes workloads remain unrecoverable after initial disk cleanup and Kubelet attempts to restart.
*   If `df -h` shows no change, or critical directories remain full after cleanup attempts.

### 10. Sources Used

*   SOURCE 1: e61f7bf5-c4aa-492e-9f0d-5f20ce47fd58
*   SOURCE 2: 91025cb2-4718-44d4-a7dd-7b8160ce2ec5
*   SOURCE 3: 42b70165-2ad0-4fab-9911-bdbb53b5676a
*   SOURCE 4: 8f3789e7-d190-418d-bfb0-76e2ca208b1f
*   SOURCE 5: 70bf8040-c2da-4848-8c03-a7c4141f94c0
*   SOURCE 6: f1f4a612-5dd5-411a-bf01-2300b164314c
*   SOURCE 7: d44efe78-0cc6-46b9-ab7d-56e2ba69784c
*   SOURCE 8: 7b3eb812-12ae-48f3-8c28-edf7745fe597
*   SOURCE 9: 75906086-b2a2-45b7-acf0-7f026c9988a2
*   SOURCE 10: 609438ea-def6-49bd-b220-07fb1b3d2b81
*   SOURCE 11: 72f47715-78d5-4f8f-a96c-281c0bd62598
*   SOURCE 12: 3429f6a2-9bb7-4a0b-8545-75ccb7170e99

In [31]:
def generate_cautious_bash_script(audit_result: dict) -> dict:
    used_chunk_ids = [
        result["chunk_id"]
        for result in audit_result["search_results"]
    ]

    used_sources = sorted(
        {
            f"{result['source_kind']} | {result['title']}"
            for result in audit_result["search_results"]
        }
    )

    prompt = f"""
You are a senior Linux SRE.

Generate a cautious Bash helper script based only on this audit result and retrieved context.

Audit question:
{audit_result["question"]}

Audit answer:
{audit_result["answer"]}

Retrieved context:
{audit_result["rag_context"]}

Return only valid JSON:

{{
  "risk_level": "low | medium | high | critical",
  "primary_issue": "short issue name",
  "root_cause_hypothesis": "short hypothesis",
  "bash_script": "complete bash script as a single string"
}}

Script rules:
- The script must be diagnostic-first.
- It may print disk usage, journal usage, large directories, failed systemd units, and recent errors.
- It may suggest safe commands as echo statements.
- It must not execute destructive cleanup automatically.
- It must not use rm -rf.
- It must not modify firewall, users, ssh keys, or package sources.
- It must include comments explaining what each section does.
- It must start with: #!/usr/bin/env bash
- It must include: set -euo pipefail
"""

    response = google_vertex_client.models.generate_content(
        model=PLANNING_MODEL,
        contents=prompt,
    )

    script_data = extract_json_object(response.text)

    return {
        "audit_id": str(uuid4()),
        "question": audit_result["question"],
        "risk_level": script_data.get("risk_level"),
        "primary_issue": script_data.get("primary_issue"),
        "root_cause_hypothesis": script_data.get("root_cause_hypothesis"),
        "audit_report": audit_result["answer"],
        "bash_script": script_data.get("bash_script"),
        "used_chunk_ids": used_chunk_ids,
        "used_sources": used_sources,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }


audit_record = generate_cautious_bash_script(ubuntu_audit_result)

print("Risk level:", audit_record["risk_level"])
print("Primary issue:", audit_record["primary_issue"])
print("Root cause hypothesis:", audit_record["root_cause_hypothesis"])
print("\nBash script:")
print(audit_record["bash_script"])

Risk level: high
Primary issue: Critical Disk Pressure
Root cause hypothesis: The root filesystem is full, primarily due to large systemd journal logs and an uncleaned apt cache, which is causing cascading service failures including Kubelet.

Bash script:
#!/usr/bin/env bash
# Cautious SRE Diagnostic Helper for Ubuntu Disk Pressure
# This script is READ-ONLY. It will not modify the system.
# It will diagnose the state and suggest safe, copy-pasteable commands based on the audit findings.

set -euo pipefail

# --- Script Preamble and Safety Check ---
echo "--- [SRE Diagnostic Helper - READ-ONLY MODE] ---"
echo "This script will perform a series of safe, read-only checks to diagnose disk pressure."
echo "It is based on audit findings pointing to journal and apt cache issues."
echo "No changes will be made to the system by this script."

if [[ $EUID -ne 0 ]]; then
  echo "
⚠️ Warning: Not running as root. Some commands requiring 'sudo' may fail."
fi

# --- Phase 1: System Diagnostics (Read-Only) ---
echo "
--- [Phase 1: Current System State] ---"

# 1. Filesystem Usage (Reference: SOURCE 3)
# The most critical first step is to confirm which filesystem is full.
echo "
=> 1. Filesystem Usage (df -h):"
df -h

# 2. Top 10 Largest Directories in /var (Reference: SOURCE 6)
# The audit points to /var as a likely source of bloat (journal, apt, kubelet).
echo "
=> 2. Top 10 Largest Directories in /var (sudo du):"
sudo du -shc /var/* 2>/dev/null | sort -rh | head -n 10

# 3. Systemd Journal Disk Usage (Reference: SOURCE 6)
# Confirmed as a likely culprit by the audit.
echo "
=> 3. Systemd Journal Disk Usage (journalctl --disk-usage):"
sudo journalctl --disk-usage

# 4. Check for Failed Services (Reference: SOURCE 9, 10)
# The audit shows Kubelet is in a restart loop. This will confirm it and check for others.
echo "
=> 4. Check for Failed Systemd Units (systemctl --failed):"
systemctl --failed --no-pager || true

# 5. Check for Files Deleted but Held Open (Reference: SOURCE 12)
# A common hidden source of disk space usage.
echo "
=> 5. List Deleted Files Still Held Open by Processes (lsof +L1):"
sudo lsof +L1 | head -n 20 || echo "  (lsof not found or no open files found)"

# 6. Recent High-Priority Journal Errors
# Filter for the exact error messages seen in the audit logs.
echo "
=> 6. Recent Journal Errors mentioning 'No space' or 'Failed':"
sudo journalctl -p err -n 25 --no-pager | grep -i 'no space\|failed' || echo "  (No recent critical errors with 'no space' or 'failed' found)"

# --- Phase 2: Suggested Mitigation Plan (Manual Execution) ---
echo "
--- [Phase 2: Suggested Safe Mitigation Plan] ---"
echo "Based on the diagnostics, the following commands are recommended."
echo "They are considered safe and target the likely culprits identified in the audit."
echo "Execute these commands MANUALLY one by one."

# Suggestions are based on SOURCE 6 and SOURCE 8
echo "
# 1. Clean the apt package cache. This is very safe and often frees significant space.
sudo apt-get clean

# 2. Shrink the systemd journal to a maximum of 500MB. This is the recommended way to clean journal logs.
sudo journalctl --vacuum-size=500M

# 3. Force logrotate to run. This will rotate and compress other logs in /var/log.
sudo logrotate -f /etc/logrotate.conf

# 4. After running cleanup commands, verify that space has been freed.
df -h

# 5. Check if critical services have stabilized. Kubelet should no longer be in a failed state.
systemctl status kubelet.service
systemctl --failed
"

# --- Phase 3: Commands to Avoid ---
echo "
--- [Phase 3: DANGER - Commands to Avoid] ---"
echo "❗️ Per runbook guidance (SOURCE 8), NEVER run the following commands:"
echo "   - rm -rf /var/log/*"
echo "   - rm -f /var/log/journal/*"
echo "Reason: This can corrupt the journal database and cause running processes to fail."

echo "
--- [End of Report] ---"

In [32]:
audit_timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

audit_report_blob_name = (
    f"{GCS_AUDIT_PREFIX}/"
    f"{audit_record['audit_id']}/"
    f"audit_report_{audit_timestamp}.md"
)

script_blob_name = (
    f"{GCS_SCRIPT_PREFIX}/"
    f"{audit_record['audit_id']}/"
    f"mitigation_helper_{audit_timestamp}.sh"
)

audit_gcs_uri = upload_text_to_gcs(
    audit_record["audit_report"],
    blob_name=audit_report_blob_name,
    content_type="text/markdown",
)

script_gcs_uri = upload_text_to_gcs(
    audit_record["bash_script"],
    blob_name=script_blob_name,
    content_type="text/x-shellscript",
)

audit_record = {
    **audit_record,
    "audit_gcs_uri": audit_gcs_uri,
    "script_gcs_uri": script_gcs_uri,
}

print("Audit report saved to:")
print(audit_gcs_uri)

print("\nBash helper script saved to:")
print(script_gcs_uri)

Audit report saved to:
gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/audits/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/audit_report_20260702_154807.md

Bash helper script saved to:
gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/scripts/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/mitigation_helper_20260702_154807.sh

In [33]:
bigquery_client.query(
    f"TRUNCATE TABLE `{audit_table_ref}`",
    location=dataset.location,
).result()

audit_errors = bigquery_client.insert_rows_json(
    audit_table_ref,
    [audit_record],
)

if audit_errors:
    print("Audit insert errors:")
    print(audit_errors)
else:
    print("Inserted audit rows: 1")

Inserted audit rows: 1

In [34]:
test_questions = [
    "SSH auth log shows many failed password attempts and invalid users. What is the risk?",
    "dmesg reports PCIe device reset and driver timeout. What should be checked?",
    "systemd service keeps restarting after config change and port binding error.",
    "NetworkManager reports DNS timeout and interface link flaps.",
]

for question in test_questions:
    print("\n" + "=" * 100)
    print("QUESTION:")
    print(question)

    results = search_ubuntu_chunks(
        question,
        top_k=5,
    )

    for result in results:
        print(
            "distance:",
            round(result["distance"], 4),
            "| kind:",
            result["source_kind"],
            "| type:",
            result["source_type"],
            "| title:",
            result["title"],
            "| chunk:",
            result["global_chunk_number"],
        )

====================================================================================================
QUESTION:
SSH auth log shows many failed password attempts and invalid users. What is the risk?
distance: 0.2235 | kind: knowledge_document | type: runbook | title: SSH Authentication Anomaly Investigation Runbook | chunk: 87
distance: 0.2502 | kind: knowledge_document | type: runbook | title: SSH Authentication Anomaly Investigation Runbook | chunk: 88
distance: 0.2546 | kind: log_file | type: authlog | title: ubuntu-api-03 authlog log | chunk: 28
distance: 0.2594 | kind: knowledge_document | type: runbook | title: SSH Authentication Anomaly Investigation Runbook | chunk: 93
distance: 0.2598 | kind: knowledge_document | type: runbook | title: SSH Authentication Anomaly Investigation Runbook | chunk: 90

====================================================================================================
QUESTION:
dmesg reports PCIe device reset and driver timeout. What should be checked?
distance: 0.173 | kind: knowledge_document | type: runbook | title: Kernel Driver Warning and Device Reset Runbook | chunk: 105
distance: 0.2196 | kind: log_file | type: dmesg | title: ubuntu-gpu-node-02 dmesg log | chunk: 20
distance: 0.2413 | kind: knowledge_document | type: runbook | title: Kernel Driver Warning and Device Reset Runbook | chunk: 109
distance: 0.2428 | kind: knowledge_document | type: runbook | title: Kernel Driver Warning and Device Reset Runbook | chunk: 106
distance: 0.2461 | kind: knowledge_document | type: runbook | title: Kernel Driver Warning and Device Reset Runbook | chunk: 107

====================================================================================================
QUESTION:
systemd service keeps restarting after config change and port binding error.
distance: 0.2686 | kind: log_file | type: systemd | title: ubuntu-db-04 systemd log | chunk: 45
distance: 0.2781 | kind: log_file | type: systemd | title: ubuntu-db-04 systemd log | chunk: 41
distance: 0.2825 | kind: knowledge_document | type: runbook | title: Systemd Service Failure and Restart Loop Runbook | chunk: 82
distance: 0.2881 | kind: log_file | type: systemd | title: ubuntu-db-04 systemd log | chunk: 43
distance: 0.2904 | kind: knowledge_document | type: runbook | title: Systemd Service Failure and Restart Loop Runbook | chunk: 81

====================================================================================================
QUESTION:
NetworkManager reports DNS timeout and interface link flaps.
distance: 0.2213 | kind: knowledge_document | type: runbook | title: Ubuntu Network Instability and DNS Troubleshooting Runbook | chunk: 117
distance: 0.2392 | kind: log_file | type: network | title: ubuntu-edge-05 network log | chunk: 49
distance: 0.2475 | kind: knowledge_document | type: runbook | title: Ubuntu Network Instability and DNS Troubleshooting Runbook | chunk: 122
distance: 0.2518 | kind: knowledge_document | type: runbook | title: Ubuntu Network Instability and DNS Troubleshooting Runbook | chunk: 118
distance: 0.2533 | kind: knowledge_document | type: runbook | title: Ubuntu Network Instability and DNS Troubleshooting Runbook | chunk: 116

In [35]:
sql = f"""
SELECT
  source_kind,
  source_type,
  topic,
  COUNT(*) AS chunk_count,
  ROUND(AVG(chunk_char_count), 2) AS avg_chunk_chars,
  MIN(chunk_char_count) AS min_chunk_chars,
  MAX(chunk_char_count) AS max_chunk_chars
FROM `{chunk_table_ref}`
GROUP BY
  source_kind,
  source_type,
  topic
ORDER BY
  source_kind,
  chunk_count DESC
"""

chunk_analytics_df = bigquery_client.query(
    sql,
    location=dataset.location,
).to_dataframe()

chunk_analytics_df

/home/lipov/projects/Python_practice_sessions_05/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,source_kind,source_type,topic,chunk_count,avg_chunk_chars,min_chunk_chars,max_chunk_chars
0,knowledge_document,runbook,ssh_auth_anomaly,16,1014.63,347,1200
1,knowledge_document,runbook,systemd_failures,14,1058.36,712,1199
2,knowledge_document,runbook,kernel_driver_warnings,13,1051.77,882,1199
3,knowledge_document,runbook,disk_pressure,12,1073.75,437,1200
4,knowledge_document,runbook,network_instability,11,1109.45,735,1200
5,log_file,syslog,disk pressure and journal growth causing servi...,15,967.33,375,1200
6,log_file,network,network instability with DNS failures and inte...,14,1080.00,570,1200
7,log_file,authlog,SSH authentication anomaly with repeated faile...,11,1160.73,970,1200
8,log_file,dmesg,kernel driver warnings and intermittent device...,10,1108.60,790,1200
9,log_file,systemd,database service restart loop after configurat...,10,1122.80,1013,1199

In [36]:
sql = f"""
SELECT
  audit_id,
  risk_level,
  primary_issue,
  root_cause_hypothesis,
  audit_gcs_uri,
  script_gcs_uri,
  created_at
FROM `{audit_table_ref}`
ORDER BY created_at DESC
"""

audit_overview_df = bigquery_client.query(
    sql,
    location=dataset.location,
).to_dataframe()

audit_overview_df

/home/lipov/projects/Python_practice_sessions_05/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,audit_id,risk_level,primary_issue,root_cause_hypothesis,audit_gcs_uri,script_gcs_uri,created_at
0,822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8,high,Critical Disk Pressure,"The root filesystem is full, primarily due to ...",gs://leafy-guide-497515-m4-vector-assets/ubunt...,gs://leafy-guide-497515-m4-vector-assets/ubunt...,2026-07-02 15:46:30.535665+00:00

In [37]:
notebook_summary = {
    "project_id": PROJECT_ID,
    "location": LOCATION,
    "created_at": datetime.now(timezone.utc).isoformat(),
    "notebook": "64_w_google_cloud_ubuntu_log_auditor_rag.ipynb",
    "models": {
        "planning_model": PLANNING_MODEL,
        "text_model": TEXT_MODEL,
        "text_embedding_model": TEXT_EMBEDDING_MODEL,
    },
    "bigquery": {
        "dataset": DATASET_ID,
        "log_table": log_table_ref,
        "document_table": document_table_ref,
        "chunk_table": chunk_table_ref,
        "audit_table": audit_table_ref,
    },
    "cloud_storage": {
        "log_prefix": f"gs://{BUCKET_NAME}/{GCS_LOG_PREFIX}/{timestamp}",
        "audit_gcs_uri": audit_gcs_uri,
        "script_gcs_uri": script_gcs_uri,
        "local_files_saved": False,
    },
    "log_count": len(generated_logs),
    "knowledge_document_count": len(knowledge_documents),
    "chunk_count": len(chunk_rows),
    "audit_record": audit_record,
    "chunk_analytics": chunk_analytics_df.to_dict(orient="records"),
}

summary_json = json.dumps(
    notebook_summary,
    indent=2,
    ensure_ascii=False,
    default=str,
)

summary_blob_name = (
    f"{GCS_SUMMARY_PREFIX}/"
    f"{audit_record['audit_id']}/"
    f"summary_{audit_timestamp}.json"
)

summary_gcs_uri = upload_text_to_gcs(
    summary_json,
    blob_name=summary_blob_name,
    content_type="application/json",
)

print("Notebook summary saved to:")
print(summary_gcs_uri)

Notebook summary saved to:
gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/summaries/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/summary_20260702_154807.json

In [38]:
print("Ubuntu Log Auditor RAG notebook completed.")
print("=" * 100)

print("Generated logs:", len(generated_logs))
print("Knowledge documents:", len(knowledge_documents))
print("Chunks:", len(chunk_rows))

print("\nBigQuery tables:")
print("-", log_table_ref)
print("-", document_table_ref)
print("-", chunk_table_ref)
print("-", audit_table_ref)

print("\nGCS outputs:")
print("Logs prefix:", f"gs://{BUCKET_NAME}/{GCS_LOG_PREFIX}/{timestamp}")
print("Audit report:", audit_gcs_uri)
print("Bash helper script:", script_gcs_uri)
print("Summary:", summary_gcs_uri)

print("\nAudit result:")
print("Risk level:", audit_record["risk_level"])
print("Primary issue:", audit_record["primary_issue"])
print("Root cause hypothesis:", audit_record["root_cause_hypothesis"])

print("\nAudit report preview:")
print(audit_record["audit_report"][:1600])

print("\nBash script preview:")
print(audit_record["bash_script"][:1600])

print("\nNo local files were saved.")

Ubuntu Log Auditor RAG notebook completed.
====================================================================================================
Generated logs: 5
Knowledge documents: 5
Chunks: 126

BigQuery tables:
- leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_files
- leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_knowledge_documents
- leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_log_and_knowledge_chunks
- leafy-guide-497515-m4.ubuntu_log_auditor_rag.ubuntu_audit_reports

GCS outputs:
Logs prefix: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/logs/20260702_151254
Audit report: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/audits/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/audit_report_20260702_154807.md
Bash helper script: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/scripts/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/mitigation_helper_20260702_154807.sh
Summary: gs://leafy-guide-497515-m4-vector-assets/ubuntu-log-auditor/summaries/822cafc5-c8a2-47d0-b3c3-bed2e7cf74b8/summary_20260702_154807.json

Audit result:
Risk level: high
Primary issue: Critical Disk Pressure
Root cause hypothesis: The root filesystem is full, primarily due to large systemd journal logs and an uncleaned apt cache, which is causing cascading service failures including Kubelet.

Audit report preview:
Here is an audit report for the unstable Ubuntu worker server:

### 1. Executive Summary

The Ubuntu worker server `ubuntu-worker-01` is experiencing critical instability due to severe disk pressure. Multiple services, including Kubernetes Kubelet, systemd-journald, apt, and snapd, are failing to write data, leading to repeated restarts and service unavailability. The root cause is a "No space left on device" condition on the primary filesystem, exacerbated by large journal logs and apt cache issues.

### 2. Most Likely Primary Issue

The primary issue is a **critical "No space left on device" condition** on the root filesystem (likely `/` or `/var`), leading to cascading service failures and instability. This is directly causing services to crash, fail to start, and enter restart loops, as well as preventing system logging and package management operations.

### 3. Evidence from Log Chunks

The following log entries confirm the disk pressure and its impact:

*   **"No space left on device" errors:**
    *   `Oct 26 08:38:47 ubuntu-worker-01 kernel: [ 7632.987654] EXT4-fs (sda1): failing file system due to no space left on device` (SOURCE 4)
    *   `Oct 26 08:38:47 ubuntu-worker-01 kubelet[23601]: E1026 08:38:47.123987 23601 writer.go:108] "Failed to write checkpoint" err="failed to write checkpoint object to disk: write /var/lib/kubelet/kubeadm-flags.env.checkpoint2108882987: no space left on device"` (SOURCE 4)
    *   `Oct 26 08:38:47 ubuntu-worker-01 systemd-journald[489]: Failed to write entry (22 items, 638 bytes), ignoring: No space left on device` (SOURCE 4)
    *

Bash script preview:
#!/usr/bin/env bash
# Cautious SRE Diagnostic Helper for Ubuntu Disk Pressure
# This script is READ-ONLY. It will not modify the system.
# It will diagnose the state and suggest safe, copy-pasteable commands based on the audit findings.

set -euo pipefail

# --- Script Preamble and Safety Check ---
echo "--- [SRE Diagnostic Helper - READ-ONLY MODE] ---"
echo "This script will perform a series of safe, read-only checks to diagnose disk pressure."
echo "It is based on audit findings pointing to journal and apt cache issues."
echo "No changes will be made to the system by this script."

if [[ $EUID -ne 0 ]]; then
  echo "
⚠️ Warning: Not running as root. Some commands requiring 'sudo' may fail."
fi

# --- Phase 1: System Diagnostics (Read-Only) ---
echo "
--- [Phase 1: Current System State] ---"

# 1. Filesystem Usage (Reference: SOURCE 3)
# The most critical first step is to confirm which filesystem is full.
echo "
=> 1. Filesystem Usage (df -h):"
df -h

# 2. Top 10 Largest Directories in /var (Reference: SOURCE 6)
# The audit points to /var as a likely source of bloat (journal, apt, kubelet).
echo "
=> 2. Top 10 Largest Directories in /var (sudo du):"
sudo du -shc /var/* 2>/dev/null | sort -rh | head -n 10

# 3. Systemd Journal Disk Usage (Reference: SOURCE 6)
# Confirmed as a likely culprit by the audit.
echo "
=> 3. Systemd Journal Disk Usage (journalctl --disk-usage):"
sudo journalctl --disk-usage

# 4. Check for Failed Services (Reference: SOURCE 9, 10)
# The audit shows Kubelet is in a restart loop. This will confirm it and check for others.
echo "
=> 4. Check for Faile

No local files were saved.